# This workflow outlines tasks that are ran when a new tag is made, typically releasing a new plugin version.

name: "Tag: Release"

on:
  push:
    tags:
      - "v*.*.*.*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: >-
          echo "::set-output name=TAG::$(echo ${{ github.ref }} | sed 's/refs\/tags\///' | sed 's/v//')"

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        working-directory: src/GoodFriend.Plugin
        run: dotnet restore

      - name: Download Dalamud Library
        working-directory: src/GoodFriend.Plugin
        run: |
          export IsCI=true
          wget -O Dalamud.zip https://goatcorp.github.io/dalamud-distrib/latest.zip
          unzip -o -d Dalamud Dalamud.zip

      - name: Build Plugin
        shell: bash
        working-directory: src/GoodFriend.Plugin
        run: |
          dotnet build --configuration Release --nologo -p:AssemblyVersion=${{ steps.tag_name.outputs.TAG }} -p:AssemblyInformationalVersion=${{ steps.tag_name }}
          sha512sum bin/Release/GoodFriend/latest.zip  >> checksums.txt
          sha512sum bin/Release/GoodFriend/GoodFriend.json >> checksums.txt
          cat checksums.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        working-directory: src/GoodFriend.Plugin
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            bin/Release/GoodFriend/latest.zip
            bin/Release/GoodFriend/GoodFriend.json
            checksums.txt
